### ISSUE TITLE
Can't manually close invmenu inventory

### ISSUE THREAD

**Issue by xxAROX** [Muqsit/InvMenu#131]
`$transaction->getPlayer()->removeWindow($transaction->getAction()->getInventory());` doesn't work
`$transaction->getAction()->getInventory()->close($transaction->getPlayer());` works, but i cant open any kind of inventories after call this

PS.: I'm using WarterdogPE, idk if that's an issue

**Comment by callumrawlinson** [comment]
Hello! 

please read the wiki but im sure this will help!

Removed methods
InvMenu::getListener() — There was no reason to expose the listener.
InvMenu::getInventoryCloseListener() — Again, no reason to expose the listener.
Removed classes
BaseFakeInventory, ChestInventory, DoubleChestInventory, HopperInventory, SingleBlockInventory — These are no longer needed. BaseFakeInventory was infact a poorly-written class with a few player-related property handlers in it (basically, a part of the API lied in the inventory class). The only reason behind these inventory classes were to define their network types which is no longer necessary due to the change in pattern to register new InvMenu types. All of these classes have been replaced by a single invMenuInventory class.
HolderData — This has been replaced by a much better written PlayerSession class.
DelayedFakeBlockDataNotifyTask — The whole reason behind having this was to work-around the issue of sending double chest inventories to the client. The client would take time to render the "pairing" and this task assumed the pairing took up to 5 ticks (which actually was a really bad estimation). This issue has been solved by handling NetworkStackLatencyPacket (thanks dktapps).

**Comment by callumrawlinson** [comment]
@xxAROX **please read here** https://github.com/Muqsit/InvMenu/wiki and click on the version you have on the sidebar (either 3.0 or 4.0)

**Comment by callumrawlinson** [comment]
@xxAROX  here is how you do it https://github.com/Muqsit/InvMenu#listening-players-closing-or-no-longer-viewing-the-inventory

**Comment by callumrawlinson** [comment]
@xxAROX if this doesnt work try this plugin also by @Muqsit  which is available here: https://github.com/Muqsit/InvCrashFix

**Comment by xxAROX** [comment]
okay i'll try

**Comment by xxAROX** [comment]
works, thanks

**Comment by xxAROX** [comment]
> 
> 
> @xxAROX if this doesnt work try this plugin also by @Muqsit which is available here: https://github.com/Muqsit/InvCrashFix

@Muqsit maybe implement that into InvMenu?
