### ISSUE TITLE
Add support for entity inventories

### ISSUE THREAD

**Issue by thebigsmileXD** [Muqsit/InvMenu#144]
As talked about on Discord

The following "prevents" it since https://github.com/Muqsit/InvMenu/blob/4.0/src/muqsit/invmenu/inventory/InvMenuInventory.php implements a block inventory:

https://github.com/Muqsit/InvMenu/blob/4.0/src/muqsit/invmenu/InvMenu.php#L150

**Comment by Muqsit** [comment]
Since v4.5.0, it is possible to register entity inventories by using the `InvMenuTypeBuilders::ACTOR_FIXED()` builder (see [ActorInvMenuTypeBuilderTrait](https://github.com/Muqsit/InvMenu/blob/57ea981af2fe38dbd3ef730a68c8e8a71baa1740/src/muqsit/invmenu/type/util/builder/ActorInvMenuTypeBuilderTrait.php#L28-L35) to modify metadata properties of the actor-backed inventory).
```php
// make InvMenu::create(InvMenu::TYPE_CHEST) create a minecart with chest inventory:
InvMenuHandler::getTypeRegistry()->register(InvMenu::TYPE_CHEST, InvMenuTypeBuilders::ACTOR_FIXED()
	->setActorIdentifier(EntityIds::CHEST_MINECART)
	->setNetworkWindowType(WindowTypes::CONTAINER)
	->setSize(27)
->build());
```

Actor/entity-backed inventories offer several advantages over block-backed inventories:
1. Since they are entities, they can be completely invisible. The library doesn't need to spawn the inventory outside the player's FOV.
2. Players cannot abuse menus to "levitate" in the air by standing on a fake chest block.
3. IIRC entity-backed inventories do not automatically close when a player moves out of range (although this does not seem to be the case for the minecart with chest menu registered above).

However, replacing block-backed inventories with entity-backed inventories increases the maintenance cost of this library. From [BedrockProtocol](https://github.com/pmmp/BedrockProtocol)'s commit history, [AddActorPacket](https://github.com/pmmp/BedrockProtocol/commits/master/src/AddActorPacket.php) underwent changes during 1.19.10, 1.19.20, and 1.19.40 (most recent change was 4 months ago). In contrast, [BlockActorDataPacket](https://github.com/pmmp/BedrockProtocol/commits/master/src/BlockActorDataPacket.php)'s property list has remained unchanged for more than a year (in fact, the last change was a property being renamed).

**Comment by inxomnyaa** [comment]
> Players cannot abuse menus to "levitate" in the air by standing on a fake chest block.

@dries-c This might be interesting for @NetherGamesMC

As for the maintenance cost, i am surprised they still change stuff around. Depending on the scale of changes and my spare time i might be able to coauthor some updates in the future.
