### ISSUE TITLE
[Help Need] Linux php-ds 

### ISSUE THREAD

**Issue by JustSxm** [Muqsit/InvMenu#151]
Hey, so to create plugins ive been using a windows machine where the binaries are already existing. The problem with that is that ds was already in the extensions and ready to use (I use InvMenu as virion). Although on Linux, it is not. This cause the issue that the plugin just cause an internal server error on join. Is there an easy way to include php-ds? It is to note that the host ive taken does not have ssh, only sftp. I've tried to build php-ds on a linux vm and then take it from there to send it into the host, but that doesnt work so I'm a bit lost on how I could make this work.

I know this isn't related to the plugin itself, but I would love having a hand on this one, 
Thanks

**Comment by Muqsit** [comment]
PocketMine-MP dropped support for php-ds due to lack of its maintenance and its unstable nature potentially causing serious loss in data (I wouldn't recommend anyone make use of it either).
Reference: https://github.com/pmmp/php-build-scripts/commit/855d00960ebe53fa5c0f71d6cd9b6588c51731cc

As for InvMenu, all builds made since this commit no longer depend on php-ds: https://github.com/Muqsit/InvMenu/commit/af247cf4b5d43b72c5a3fff74d13898bcf118cb1

**Comment by JustSxm** [comment]
I was running on an old InvMenu virion like an idiot. Thank you
