### ISSUE TITLE
Cancel inventory close

### ISSUE THREAD

**Issue by EmporiumDevelopment** [Muqsit/InvMenu#200]
is it possible to stop a player closing an inventory unless they do something in the inventory?

**Comment by Muqsit** [comment]
InvMenu's inventory close listener uses PocketMine's [InventoryCloseEvent](https://github.com/pmmp/PocketMine-MP/blob/38d6284671e8b657ba557e765a6c29b24a7705f5/src/event/inventory/InventoryCloseEvent.php) underneath, which does not implement `pocketmine\event\Cancellable`, so disallowing players from closing an inventory isn't possible.
AFAIK, closing inventories is client-sided — when a player closes an inventory, their client merely notifies the server of the action rather than confirming the action with the server, so this may not be possible at the moment due to the game's limitations.
